import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  users: defineTable({
    tokenIdentifier: v.string(),
    clerkUserId: v.string(),
    email: v.optional(v.string()),
    name: v.optional(v.string()),
    savedCardIds: v.array(v.string()),
    activeCardIds: v.array(v.string()),
    firstUseAt: v.number(),
    lastSeenAt: v.number(),
    lastMerchant: v.string(),
    lastPurchaseType: v.string(),
    lastWinningRoute: v.string(),
  }).index("by_tokenIdentifier", ["tokenIdentifier"]),
  banks: defineTable({
    bankKey: v.string(),
    name: v.string(),
    country: v.string(),
    officialWebsite: v.string(),
    status: v.union(v.literal("covered"), v.literal("partial"), v.literal("planned")),
    checkedAt: v.number(),
  }).index("by_bankKey", ["bankKey"]),
  cardProducts: defineTable({
    cardKey: v.string(),
    bankId: v.id("banks"),
    name: v.string(),
    shortName: v.string(),
    productUrl: v.string(),
    rewardCurrency: v.string(),
    coverage: v.union(v.literal("catalogued"), v.literal("direct-rules"), v.literal("routed")),
    status: v.union(v.literal("active"), v.literal("discontinued"), v.literal("unverified")),
    checkedAt: v.number(),
  }).index("by_cardKey", ["cardKey"]).index("by_bank", ["bankId"]),
  directRewardRules: defineTable({
    ruleKey: v.string(),
    cardKey: v.string(),
    priority: v.number(),
    purchaseTypes: v.array(v.string()),
    paymentModes: v.array(v.union(v.literal("online"), v.literal("store"))),
    merchantIncludes: v.array(v.string()),
    outcome: v.union(v.literal("percentage"), v.literal("points"), v.literal("excluded")),
    rate: v.optional(v.number()),
    spendBlock: v.optional(v.number()),
    earnPerBlock: v.optional(v.number()),
    usageMetric: v.optional(v.literal("monthly-category-spend")),
    spendTierCap: v.optional(v.number()),
    earnPerBlockWithinTier: v.optional(v.number()),
    earnPerBlockAboveTier: v.optional(v.number()),
    earnPerBlockWhenUsageUnknown: v.optional(v.number()),
    rewardCurrency: v.string(),
    pointValueMin: v.number(),
    pointValueMax: v.number(),
    valueCap: v.optional(v.number()),
    matchedRule: v.string(),
    matchedRuleWithinTier: v.optional(v.string()),
    matchedRuleSplitTier: v.optional(v.string()),
    matchedRuleUsageUnknown: v.optional(v.string()),
    caveat: v.optional(v.string()),
    caveatUsageKnown: v.optional(v.string()),
    caveatUsageUnknown: v.optional(v.string()),
    sourceUrl: v.string(),
    checkedAt: v.number(),
    validFrom: v.optional(v.number()),
    validUntil: v.optional(v.number()),
    version: v.number(),
    status: v.union(v.literal("draft"), v.literal("estimate"), v.literal("approved"), v.literal("retired")),
  })
    .index("by_card", ["cardKey"])
    .index("by_card_and_status", ["cardKey", "status"])
    .index("by_ruleKey_version", ["ruleKey", "version"]),
  redemptionProfiles: defineTable({
    profileKey: v.string(),
    cardKey: v.string(),
    rewardCurrency: v.string(),
    version: v.number(),
    status: v.union(v.literal("draft"), v.literal("approved"), v.literal("retired")),
    checkedAt: v.number(),
  }).index("by_cardKey_and_rewardCurrency", ["cardKey", "rewardCurrency"]).index("by_profileKey_and_version", ["profileKey", "version"]),
  redemptionOptions: defineTable({
    profileId: v.id("redemptionProfiles"),
    optionKey: v.string(),
    label: v.string(),
    unitsPerReward: v.number(),
    rupeesPerUnit: v.number(),
    valueType: v.union(v.literal("guaranteed"), v.literal("estimated")),
    assumption: v.optional(v.string()),
    rulesSourceUrl: v.string(),
    valueSourceUrl: v.string(),
    valueSourceKind: v.union(v.literal("official"), v.literal("expert")),
    checkedAt: v.number(),
    validFrom: v.optional(v.number()),
    validUntil: v.optional(v.number()),
  }).index("by_profileId", ["profileId"]),
  paymentPlatforms: defineTable({
    platformKey: v.string(),
    name: v.string(),
    kind: v.union(v.literal("direct"), v.literal("bank-portal"), v.literal("voucher-platform")),
    operator: v.string(),
    officialUrl: v.string(),
    status: v.union(v.literal("active"), v.literal("unverified"), v.literal("retired")),
    checkedAt: v.number(),
  }).index("by_platformKey", ["platformKey"]),
  merchants: defineTable({
    merchantKey: v.string(),
    name: v.string(),
    category: v.string(),
    officialUrl: v.optional(v.string()),
  }).index("by_merchantKey", ["merchantKey"]),
  officialSources: defineTable({
    sourceKey: v.string(),
    publisher: v.string(),
    title: v.string(),
    url: v.string(),
    kind: v.union(v.literal("product-page"), v.literal("terms-page"), v.literal("pdf"), v.literal("platform-page")),
    retrievedAt: v.number(),
    contentHash: v.optional(v.string()),
  }).index("by_sourceKey", ["sourceKey"]),
  routeRules: defineTable({
    routeKey: v.string(),
    cardId: v.id("cardProducts"),
    platformId: v.id("paymentPlatforms"),
    merchantId: v.optional(v.id("merchants")),
    sourceId: v.id("officialSources"),
    routeType: v.union(v.literal("direct"), v.literal("portal"), v.literal("voucher")),
    ruleClass: v.union(v.literal("core-benefit"), v.literal("portal-benefit"), v.literal("voucher-benefit")),
    purchaseType: v.union(v.literal("shopping"), v.literal("flight"), v.literal("hotel"), v.literal("dining"), v.literal("utility"), v.literal("insurance"), v.literal("fuel"), v.literal("rent"), v.literal("education"), v.literal("jewellery"), v.literal("railway"), v.literal("government"), v.literal("gaming"), v.literal("toll"), v.literal("gift-card"), v.literal("emi"), v.literal("general")),
    paymentMode: v.union(v.literal("online"), v.literal("store"), v.literal("both")),
    baseSpend: v.number(),
    baseEarn: v.number(),
    multiplier: v.number(),
    rewardCurrency: v.string(),
    pointValueMin: v.number(),
    pointValueMax: v.number(),
    capValue: v.optional(v.number()),
    capPeriod: v.optional(v.union(v.literal("day"), v.literal("month"), v.literal("year"))),
    capUnit: v.optional(v.string()),
    domesticFeePerPassengerLeg: v.optional(v.number()),
    internationalFeePerPassengerLeg: v.optional(v.number()),
    effortSteps: v.number(),
    instructions: v.array(v.string()),
    evidence: v.string(),
    checkedAt: v.number(),
    validFrom: v.optional(v.number()),
    validUntil: v.optional(v.number()),
    version: v.number(),
    status: v.union(v.literal("draft"), v.literal("approved"), v.literal("retired")),
  }).index("by_routeKey_version", ["routeKey", "version"]).index("by_status", ["status"]).index("by_card", ["cardId"]),
  cardRequests: defineTable({
    cardName: v.string(),
    normalizedName: v.string(),
    requestedAt: v.number(),
  }).index("by_normalizedName", ["normalizedName"]),
  recommendationFeedback: defineTable({
    firstName: v.string(),
    merchant: v.string(),
    amount: v.number(),
    purchaseType: v.string(),
    paymentMode: v.string(),
    winningRouteId: v.string(),
    winningRouteTitle: v.string(),
    winningCard: v.string(),
    verdict: v.union(v.literal("useful"), v.literal("unsure"), v.literal("wrong")),
    note: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_createdAt", ["createdAt"]),
  rewardRules: defineTable({
    ruleKey: v.string(),
    version: v.number(),
    cardId: v.string(),
    channel: v.string(),
    purchaseType: v.union(v.literal("shopping"), v.literal("flight"), v.literal("hotel")),
    multiplier: v.number(),
    baseSpend: v.optional(v.number()),
    baseEarn: v.optional(v.number()),
    pointValueMin: v.number(),
    pointValueMax: v.number(),
    sourceUrl: v.string(),
    sourceLabel: v.string(),
    evidence: v.string(),
    caveat: v.optional(v.string()),
    checkedAt: v.number(),
    status: v.union(v.literal("proposed"), v.literal("approved"), v.literal("retired")),
    createdAt: v.number(),
    approvedAt: v.optional(v.number()),
  })
    .index("by_status", ["status"])
    .index("by_ruleKey_version", ["ruleKey", "version"]),
  sourceDocuments: defineTable({
    sourceKey: v.string(),
    cardId: v.string(),
    url: v.string(),
    title: v.string(),
    kind: v.union(v.literal("html"), v.literal("pdf")),
    authority: v.union(v.literal("product"), v.literal("programme"), v.literal("terms"), v.literal("service-guide"), v.literal("key-facts")),
    contentHash: v.string(),
    pageCount: v.optional(v.number()),
    retrievedAt: v.number(),
    parserVersion: v.string(),
  }).index("by_sourceKey", ["sourceKey"]),
  ruleProposals: defineTable({
    proposalKey: v.string(),
    ingestionVersion: v.string(),
    cardId: v.string(),
    ruleType: v.union(v.literal("base-earn"), v.literal("portal-multiplier"), v.literal("exclusion"), v.literal("spend-cap"), v.literal("redemption-value"), v.literal("portal-fee")),
    purchaseType: v.optional(v.string()),
    channel: v.optional(v.string()),
    value: v.number(),
    unit: v.string(),
    conditions: v.array(v.string()),
    evidence: v.string(),
    sourceDocumentId: v.id("sourceDocuments"),
    sourcePage: v.optional(v.number()),
    flags: v.array(v.string()),
    status: v.union(v.literal("proposed"), v.literal("approved"), v.literal("rejected")),
    proposedAt: v.number(),
    reviewedAt: v.optional(v.number()),
    reviewerNote: v.optional(v.string()),
  })
    .index("by_status", ["status"])
    .index("by_proposalKey", ["proposalKey"]),
  cardRuleCoverage: defineTable({
    cardId: v.string(),
    purchaseType: v.string(),
    channel: v.union(v.literal("direct"), v.literal("travel-agent")),
    status: v.union(v.literal("verified"), v.literal("excluded"), v.literal("conditional")),
    evidenceProposalKeys: v.array(v.string()),
    checkedAt: v.number(),
    reviewedAt: v.number(),
  }).index("by_cardId_and_purchaseType_and_channel", ["cardId", "purchaseType", "channel"]),
});
